version: '1'
services:
  app:
    build: ./web
    links:
      - db
    ports: 
      - "5000:5000"
    environment:
      - SQL_USER=root
      - SQL_PASSWD=root
      - SQL_URL=db
      - SQL_DB=moviedb
    depends_on:
      db : 
        condition : service_healthy
    container_name : app

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sqls/moviedbdump.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: db
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --database=moviedb --execute \"SELECT * FROM who_directed;\""
      interval: 10s
      timeout: 30s
      retries: 10
